
// This file has been generated by the GUI designer. Do not modify.
namespace Fluxmath {
	public partial class Ohm {
		private global::Gtk.VBox vbox4;

		private global::Gtk.VBox vbox6;

		private global::Gtk.HBox hbox11;

		private global::Gtk.VBox vbox9;

		private global::Gtk.Label label223;

		private global::Gtk.Entry input_voltaje;

		private global::Gtk.VBox vbox12;

		private global::Gtk.Label label5;

		private global::Gtk.Entry input_resistencia;

		private global::Gtk.VBox vbox13;

		private global::Gtk.Label label9;

		private global::Gtk.Entry output_corriente;

		private global::Gtk.HBox hbox10;

		private global::Gtk.VBox vbox7;

		private global::Gtk.Label label3;

		private global::Gtk.Entry input_corriente;

		private global::Gtk.VBox vbox11;

		private global::Gtk.Label label6;

		private global::Gtk.Entry input_resistencia1;

		private global::Gtk.VBox vbox14;

		private global::Gtk.Label label10;

		private global::Gtk.Entry output_voltaje;

		private global::Gtk.HBox hbox9;

		private global::Gtk.VBox vbox8;

		private global::Gtk.Label label7;

		private global::Gtk.Entry input_voltaje1;

		private global::Gtk.VBox vbox10;

		private global::Gtk.Label label8;

		private global::Gtk.Entry input_corriente1;

		private global::Gtk.VBox vbox15;

		private global::Gtk.Label label11;

		private global::Gtk.Entry output_resistencia;

		protected virtual void Build() {
			global::Stetic.Gui.Initialize(this);
			// Widget Fluxmath.Ohm
			this.Name = "Fluxmath.Ohm";
			this.Title = global::Mono.Unix.Catalog.GetString("Ohm");
			this.WindowPosition = ((global::Gtk.WindowPosition) (4));
			this.BorderWidth = ((uint) (9));
			// Container child Fluxmath.Ohm.Gtk.Container+ContainerChild
			this.vbox4 = new global::Gtk.VBox();
			this.vbox4.Name = "vbox4";
			this.vbox4.Spacing = 6;
			// Container child vbox4.Gtk.Box+BoxChild
			this.vbox6 = new global::Gtk.VBox();
			this.vbox6.Name = "vbox6";
			this.vbox6.Spacing = 6;
			// Container child vbox6.Gtk.Box+BoxChild
			this.hbox11 = new global::Gtk.HBox();
			this.hbox11.Name = "hbox11";
			this.hbox11.Spacing = 6;
			// Container child hbox11.Gtk.Box+BoxChild
			this.vbox9 = new global::Gtk.VBox();
			this.vbox9.Name = "vbox9";
			this.vbox9.Spacing = 6;
			// Container child vbox9.Gtk.Box+BoxChild
			this.label223 = new global::Gtk.Label();
			this.label223.Name = "label223";
			this.label223.LabelProp = global::Mono.Unix.Catalog.GetString("Voltaje");
			this.vbox9.Add(this.label223);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild) (this.vbox9[this.label223]));
			w1.Position = 0;
			w1.Expand = false;
			w1.Fill = false;
			// Container child vbox9.Gtk.Box+BoxChild
			this.input_voltaje = new global::Gtk.Entry();
			this.input_voltaje.CanFocus = true;
			this.input_voltaje.Name = "input_voltaje";
			this.input_voltaje.IsEditable = true;
			this.vbox9.Add(this.input_voltaje);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild) (this.vbox9[this.input_voltaje]));
			w2.Position = 1;
			w2.Expand = false;
			w2.Fill = false;
			this.hbox11.Add(this.vbox9);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild) (this.hbox11[this.vbox9]));
			w3.Position = 0;
			w3.Expand = false;
			w3.Fill = false;
			// Container child hbox11.Gtk.Box+BoxChild
			this.vbox12 = new global::Gtk.VBox();
			this.vbox12.Name = "vbox12";
			this.vbox12.Spacing = 6;
			// Container child vbox12.Gtk.Box+BoxChild
			this.label5 = new global::Gtk.Label();
			this.label5.Name = "label5";
			this.label5.LabelProp = global::Mono.Unix.Catalog.GetString("Resistencia");
			this.vbox12.Add(this.label5);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild) (this.vbox12[this.label5]));
			w4.Position = 0;
			w4.Expand = false;
			w4.Fill = false;
			// Container child vbox12.Gtk.Box+BoxChild
			this.input_resistencia = new global::Gtk.Entry();
			this.input_resistencia.CanFocus = true;
			this.input_resistencia.Name = "input_resistencia";
			this.input_resistencia.IsEditable = true;
			this.vbox12.Add(this.input_resistencia);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild) (this.vbox12[this.input_resistencia]));
			w5.Position = 1;
			w5.Expand = false;
			w5.Fill = false;
			this.hbox11.Add(this.vbox12);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild) (this.hbox11[this.vbox12]));
			w6.Position = 1;
			w6.Expand = false;
			w6.Fill = false;
			// Container child hbox11.Gtk.Box+BoxChild
			this.vbox13 = new global::Gtk.VBox();
			this.vbox13.Name = "vbox13";
			this.vbox13.Spacing = 6;
			// Container child vbox13.Gtk.Box+BoxChild
			this.label9 = new global::Gtk.Label();
			this.label9.LabelProp = global::Mono.Unix.Catalog.GetString("Corriente");
			this.vbox13.Add(this.label9);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild) (this.vbox13[this.label9]));
			w7.Position = 0;
			w7.Expand = false;
			w7.Fill = false;
			// Container child vbox13.Gtk.Box+BoxChild
			this.output_corriente = new global::Gtk.Entry();
			this.output_corriente.CanFocus = true;
			this.output_corriente.Name = "output_corriente";
			this.output_corriente.Text = global::Mono.Unix.Catalog.GetString("Corriente (A)");
			this.output_corriente.IsEditable = false;
			this.vbox13.Add(this.output_corriente);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild) (this.vbox13[this.output_corriente]));
			w8.Position = 1;
			w8.Expand = false;
			w8.Fill = false;
			this.hbox11.Add(this.vbox13);
			global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild) (this.hbox11[this.vbox13]));
			w9.Position = 2;
			w9.Expand = false;
			w9.Fill = false;
			this.vbox6.Add(this.hbox11);
			global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild) (this.vbox6[this.hbox11]));
			w10.Position = 0;
			w10.Expand = false;
			w10.Fill = false;
			// Container child vbox6.Gtk.Box+BoxChild
			this.hbox10 = new global::Gtk.HBox();
			this.hbox10.Name = "hbox10";
			this.hbox10.Spacing = 6;
			// Container child hbox10.Gtk.Box+BoxChild
			this.vbox7 = new global::Gtk.VBox();
			this.vbox7.Name = "vbox7";
			this.vbox7.Spacing = 6;
			// Container child vbox7.Gtk.Box+BoxChild
			this.label3 = new global::Gtk.Label();
			this.label3.Name = "label3";
			this.label3.LabelProp = global::Mono.Unix.Catalog.GetString("Corriente");
			this.vbox7.Add(this.label3);
			global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild) (this.vbox7[this.label3]));
			w11.Position = 0;
			w11.Expand = false;
			w11.Fill = false;
			// Container child vbox7.Gtk.Box+BoxChild
			this.input_corriente = new global::Gtk.Entry();
			this.input_corriente.CanFocus = true;
			this.input_corriente.Name = "input_corriente";
			this.input_corriente.IsEditable = true;
			this.vbox7.Add(this.input_corriente);
			global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild) (this.vbox7[this.input_corriente]));
			w12.Position = 1;
			w12.Expand = false;
			w12.Fill = false;
			this.hbox10.Add(this.vbox7);
			global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild) (this.hbox10[this.vbox7]));
			w13.Position = 0;
			w13.Expand = false;
			w13.Fill = false;
			// Container child hbox10.Gtk.Box+BoxChild
			this.vbox11 = new global::Gtk.VBox();
			this.vbox11.Name = "vbox11";
			this.vbox11.Spacing = 6;
			// Container child vbox11.Gtk.Box+BoxChild
			this.label6 = new global::Gtk.Label();
			this.label6.Name = "label6";
			this.label6.LabelProp = global::Mono.Unix.Catalog.GetString("Resistencia");
			this.vbox11.Add(this.label6);
			global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild) (this.vbox11[this.label6]));
			w14.Position = 0;
			w14.Expand = false;
			w14.Fill = false;
			// Container child vbox11.Gtk.Box+BoxChild
			this.input_resistencia1 = new global::Gtk.Entry();
			this.input_resistencia1.CanFocus = true;
			this.input_resistencia1.Name = "input_resistencia1";
			this.input_resistencia1.IsEditable = true;
			this.vbox11.Add(this.input_resistencia1);
			global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild) (this.vbox11[this.input_resistencia1]));
			w15.Position = 1;
			w15.Expand = false;
			w15.Fill = false;
			this.hbox10.Add(this.vbox11);
			global::Gtk.Box.BoxChild w16 = ((global::Gtk.Box.BoxChild) (this.hbox10[this.vbox11]));
			w16.Position = 1;
			w16.Expand = false;
			w16.Fill = false;
			// Container child hbox10.Gtk.Box+BoxChild
			this.vbox14 = new global::Gtk.VBox();
			this.vbox14.Name = "vbox14";
			this.vbox14.Spacing = 6;
			// Container child vbox14.Gtk.Box+BoxChild
			this.label10 = new global::Gtk.Label();
			this.label10.Name = "label10";
			this.label10.LabelProp = global::Mono.Unix.Catalog.GetString("Voltaje");
			this.vbox14.Add(this.label10);
			global::Gtk.Box.BoxChild w17 = ((global::Gtk.Box.BoxChild) (this.vbox14[this.label10]));
			w17.Position = 0;
			w17.Expand = false;
			w17.Fill = false;
			// Container child vbox14.Gtk.Box+BoxChild
			this.output_voltaje = new global::Gtk.Entry();
			this.output_voltaje.CanFocus = true;
			this.output_voltaje.Name = "output_voltaje";
			this.output_voltaje.Text = global::Mono.Unix.Catalog.GetString("Voltaje (V)");
			this.output_voltaje.IsEditable = false;
			this.vbox14.Add(this.output_voltaje);
			global::Gtk.Box.BoxChild w18 = ((global::Gtk.Box.BoxChild) (this.vbox14[this.output_voltaje]));
			w18.Position = 1;
			w18.Expand = false;
			w18.Fill = false;
			this.hbox10.Add(this.vbox14);
			global::Gtk.Box.BoxChild w19 = ((global::Gtk.Box.BoxChild) (this.hbox10[this.vbox14]));
			w19.Position = 2;
			w19.Expand = false;
			w19.Fill = false;
			this.vbox6.Add(this.hbox10);
			global::Gtk.Box.BoxChild w20 = ((global::Gtk.Box.BoxChild) (this.vbox6[this.hbox10]));
			w20.Position = 1;
			w20.Expand = false;
			w20.Fill = false;
			// Container child vbox6.Gtk.Box+BoxChild
			this.hbox9 = new global::Gtk.HBox();
			this.hbox9.Name = "hbox9";
			this.hbox9.Spacing = 6;
			// Container child hbox9.Gtk.Box+BoxChild
			this.vbox8 = new global::Gtk.VBox();
			this.vbox8.Name = "vbox8";
			this.vbox8.Spacing = 6;
			// Container child vbox8.Gtk.Box+BoxChild
			this.label7 = new global::Gtk.Label();
			this.label7.Name = "label7";
			this.label7.LabelProp = global::Mono.Unix.Catalog.GetString("Voltaje (V)");
			this.vbox8.Add(this.label7);
			global::Gtk.Box.BoxChild w21 = ((global::Gtk.Box.BoxChild) (this.vbox8[this.label7]));
			w21.Position = 0;
			w21.Expand = false;
			w21.Fill = false;
			// Container child vbox8.Gtk.Box+BoxChild
			this.input_voltaje1 = new global::Gtk.Entry();
			this.input_voltaje1.CanFocus = true;
			this.input_voltaje1.Name = "input_voltaje1";
			this.input_voltaje1.IsEditable = true;
			this.vbox8.Add(this.input_voltaje1);
			global::Gtk.Box.BoxChild w22 = ((global::Gtk.Box.BoxChild) (this.vbox8[this.input_voltaje1]));
			w22.Position = 1;
			w22.Expand = false;
			w22.Fill = false;
			this.hbox9.Add(this.vbox8);
			global::Gtk.Box.BoxChild w23 = ((global::Gtk.Box.BoxChild) (this.hbox9[this.vbox8]));
			w23.Position = 0;
			w23.Expand = false;
			w23.Fill = false;
			// Container child hbox9.Gtk.Box+BoxChild
			this.vbox10 = new global::Gtk.VBox();
			this.vbox10.Name = "vbox10";
			this.vbox10.Spacing = 6;
			// Container child vbox10.Gtk.Box+BoxChild
			this.label8 = new global::Gtk.Label();
			this.label8.Name = "label8";
			this.label8.LabelProp = global::Mono.Unix.Catalog.GetString("Corriente");
			this.vbox10.Add(this.label8);
			global::Gtk.Box.BoxChild w24 = ((global::Gtk.Box.BoxChild) (this.vbox10[this.label8]));
			w24.Position = 0;
			w24.Expand = false;
			w24.Fill = false;
			// Container child vbox10.Gtk.Box+BoxChild
			this.input_corriente1 = new global::Gtk.Entry();
			this.input_corriente1.CanFocus = true;
			this.input_corriente1.Name = "input_corriente1";
			this.input_corriente1.IsEditable = true;
			this.vbox10.Add(this.input_corriente1);
			global::Gtk.Box.BoxChild w25 = ((global::Gtk.Box.BoxChild) (this.vbox10[this.input_corriente1]));
			w25.Position = 1;
			w25.Expand = false;
			w25.Fill = false;
			this.hbox9.Add(this.vbox10);
			global::Gtk.Box.BoxChild w26 = ((global::Gtk.Box.BoxChild) (this.hbox9[this.vbox10]));
			w26.Position = 1;
			w26.Expand = false;
			w26.Fill = false;
			// Container child hbox9.Gtk.Box+BoxChild
			this.vbox15 = new global::Gtk.VBox();
			this.vbox15.Name = "vbox15";
			this.vbox15.Spacing = 6;
			// Container child vbox15.Gtk.Box+BoxChild
			this.label11 = new global::Gtk.Label();
			this.label11.Name = "label11";
			this.label11.LabelProp = global::Mono.Unix.Catalog.GetString("Resistencia (ohm)");
			this.vbox15.Add(this.label11);
			global::Gtk.Box.BoxChild w27 = ((global::Gtk.Box.BoxChild) (this.vbox15[this.label11]));
			w27.Position = 0;
			w27.Expand = false;
			w27.Fill = false;
			// Container child vbox15.Gtk.Box+BoxChild
			this.output_resistencia = new global::Gtk.Entry();
			this.output_resistencia.CanFocus = true;
			this.output_resistencia.Name = "output_resistencia";
			this.output_resistencia.Text = global::Mono.Unix.Catalog.GetString("Resistencia");
			this.output_resistencia.IsEditable = false;
			this.vbox15.Add(this.output_resistencia);
			global::Gtk.Box.BoxChild w28 = ((global::Gtk.Box.BoxChild) (this.vbox15[this.output_resistencia]));
			w28.Position = 1;
			w28.Expand = false;
			w28.Fill = false;
			this.hbox9.Add(this.vbox15);
			global::Gtk.Box.BoxChild w29 = ((global::Gtk.Box.BoxChild) (this.hbox9[this.vbox15]));
			w29.Position = 2;
			w29.Expand = false;
			w29.Fill = false;
			this.vbox6.Add(this.hbox9);
			global::Gtk.Box.BoxChild w30 = ((global::Gtk.Box.BoxChild) (this.vbox6[this.hbox9]));
			w30.Position = 2;
			w30.Expand = false;
			w30.Fill = false;
			this.vbox4.Add(this.vbox6);
			global::Gtk.Box.BoxChild w31 = ((global::Gtk.Box.BoxChild) (this.vbox4[this.vbox6]));
			w31.PackType = ((global::Gtk.PackType) (1));
			w31.Position = 0;
			w31.Expand = false;
			w31.Fill = false;
			this.Add(this.vbox4);
			if ((this.Child != null)) {
				this.Child.ShowAll();
			}
			this.DefaultWidth = 522;
			this.DefaultHeight = 186;
			this.Show();
			this.input_voltaje.Changed += new global::System.EventHandler(this.OnInputVoltajeChanged);
			this.input_resistencia.Changed += new global::System.EventHandler(this.OnInputResistenciaChanged);
			this.input_corriente.Changed += new global::System.EventHandler(this.OnInputCorrienteChanged);
			this.input_resistencia1.Changed += new global::System.EventHandler(this.OnInputResistencia1Changed);
			this.input_voltaje1.Changed += new global::System.EventHandler(this.OnInputVoltaje1Changed);
			this.input_corriente1.Changed += new global::System.EventHandler(this.OnInputCorriente1Changed);
		}
	}
}
